### ISSUE TITLE
Not used "required" element of "JsonRpcParam" annotation

### ISSUE THREAD

**Issue by mnasyrov** [arteam/simple-json-rpc#3]
There is `required` element of `@JsonRpcParam` annotation which is not used by the implementation. Thus a method parameter is still required in a following example:

```java
@JsonRpcMethod("getData")
public String getData(@JsonRpcParam(value = "foo", required = false) String foo) {
// ...
}
```

In this case `@JsonRpcOptional` attribute works:
```java
@JsonRpcMethod("getData")
public String getData(@JsonRpcOptional @JsonRpcParam("foo") {
// ...
}
```

**Comment by arteam** [comment]
If my memory serves me right, it was the first attempt of implementing optional values as an annotation marker. I didn't like it, because using `required = false` forces the developer to add the `value` parameter to the annotation. which makes it quite verbose. After that I decided to go with the `@JsonRpcOptional` approach, which seems a little bit better and as a side-effect shuns the developer from overusing of optional parameters. I just forgot to remove the `required` parameter from `@JsonRpcParam`. Will do in the next release, so things are not so confusing.
